'use client';

import { useEffect, useRef, useState } from 'react';

type State = 'idle' | 'queued' | 'generated' | 'failed';

export function NarrativePanel({
  findingId,
  initialNarrative,
  initialStatus,
  canGenerate,
}: {
  findingId: string;
  initialNarrative: string | null;
  initialStatus: string | null;
  canGenerate: boolean;
}) {
  const [state, setState] = useState<State>(
    initialStatus === 'generated' ? 'generated' : 'idle',
  );
  const [narrative, setNarrative] = useState(initialNarrative);
  const [error, setError] = useState<string | null>(null);
  const attempts = useRef(0);

  useEffect(() => {
    if (state !== 'queued') return;
    const timer = window.setInterval(() => {
      attempts.current += 1;
      void fetch(`/api/findings/${findingId}`, { cache: 'no-store' })
        .then(async (response) => {
          if (!response.ok)
            throw new Error('Finding status could not be read.');
          return (await response.json()) as {
            data: {
              narrative: {
                status: string;
                structuredResponse?: { summary?: string } | null;
              } | null;
            };
          };
        })
        .then(({ data }) => {
          const summary = data.narrative?.structuredResponse?.summary;
          if (data.narrative?.status === 'generated' && summary) {
            window.clearInterval(timer);
            setNarrative(summary);
            setState('generated');
          } else if (attempts.current >= 75) {
            window.clearInterval(timer);
            setError(
              'Generation is taking longer than expected. Check the worker and retry.',
            );
            setState('failed');
          }
        })
        .catch(() => {
          window.clearInterval(timer);
          setError('Narrative status could not be checked. Please retry.');
          setState('failed');
        });
    }, 2_000);
    return () => window.clearInterval(timer);
  }, [findingId, state]);

  async function requestNarrative() {
    setError(null);
    attempts.current = 0;
    setState('queued');
    const response = await fetch(`/api/findings/${findingId}/narrative`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: '{}',
    }).catch(() => null);
    if (!response?.ok) {
      setError(
        'Narrative generation could not be queued. Is the worker running?',
      );
      setState('failed');
    }
  }

  return (
    <section className="workspace-section">
      <div className="section-heading">
        <div>
          <h2>Optional AI narrative</h2>
          <p aria-live="polite">
            {state === 'queued'
              ? 'Generating summary…'
              : state === 'generated'
                ? 'Generated by Gemini · no scoring authority'
                : 'Deterministic explanation available'}
          </p>
        </div>
        {canGenerate && state !== 'generated' ? (
          <button
            className="narrative-action"
            type="button"
            disabled={state === 'queued'}
            onClick={() => void requestNarrative()}
          >
            {state === 'queued'
              ? 'Generating…'
              : state === 'failed'
                ? 'Retry summary'
                : 'Generate AI summary'}
          </button>
        ) : null}
      </div>
      <div className="narrative-panel" aria-busy={state === 'queued'}>
        {state === 'queued'
          ? 'Gemini is preparing a concise evidence summary. The deterministic score remains unchanged.'
          : (narrative ??
            'The deterministic explanation above remains the available review summary.')}
      </div>
      {error ? (
        <p className="narrative-error" role="alert">
          {error}
        </p>
      ) : null}
    </section>
  );
}
